### ISSUE TITLE
Use cache fire

### ISSUE THREAD

**Issue by Batwho** [princeton-vl/infinigen#357]
Hello,

I'm trying to run the `python -m infinigen.tools.submit_asset_cache -f './fire' -n 1 -s -0 -d 184` to cache fire, but get the following error [775890_0_log.txt](https://github.com/user-attachments/files/17402393/775890_0_log.txt). 
I got the same error on both slurm and my local pc. Could you please help me check the bug?

**Comment by Batwho** [comment]
Hi @karhankayan , Just wonder is there any updates or fix on this issue?

**Comment by karhankayan** [comment]
Sorry for the late response. I fixed this and will patch soon.

**Comment by Batwho** [comment]
@karhankayan Hello, I tried again with the latest code (1.12.3) and seems like the error is still the same. Just wonder have you patched it?
