### ISSUE TITLE
Problems in running HelloWorld and HelloRoom in v1.11.0

### ISSUE THREAD

**Issue by Superviro** [princeton-vl/infinigen#373]
# Describe the bug
Hi, I encounter some bugs when using v1.11.0 to run HelloWorld and HelloRoom. After running HelloRoom, the result depth is somewhat abnormal, like the following:
![Depth_0_0_0048_0](https://github.com/user-attachments/assets/c859012c-e222-4d4f-9e0f-fdae15e1b862)
And here's the corresponding RGB image:
![Image_0_0_0048_0](https://github.com/user-attachments/assets/0e61a3d9-29dd-4219-bd03-ebf74f9e85bf)

And during running HelloWorld(during generating ground truth, to be precise), the process terminated with "AttributeError:  'NoneType' object has no attribute 'type'"

However, when I use v1.10.1 to run them again, it comes back to normal, I wonder are these new bugs introduced by the update?

### What version of the code were you using? 
v1.11.0

### What command did you run?
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True 

python -m infinigen.datagen.manage_jobs --output_folder outputs/hello_world --num_scenes 1 --specific_seed 0 \
--configs desert.gin simple.gin --pipeline_configs local_16GB.gin monocular.gin blender_gt.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False

### What are your FULL output logs?
The log that containing the error info when running ground-truth rendering:
[51995413362_0_log.txt](https://github.com/user-attachments/files/17799629/51995413362_0_log.txt)

**Comment by araistrick** [comment]
Thanks for the report, I will look into this ASAP.

**Comment by araistrick** [comment]
Should be fixed by v1.11.1

**Comment by Superviro** [comment]
> Should be fixed by v1.11.1

Thanks for the quick response! I tried it today but It seems the error when running HelloWorld still exists :(

**Comment by araistrick** [comment]
Are you sure you are able to reproduce the scrambled depthmap on v1.11? for me it seems fine 
![Depth_0_0_0048_0](https://github.com/user-attachments/assets/94e9ca89-42c4-4e46-93ff-83a922571941)

**Comment by araistrick** [comment]
I see, this likely is because of the opengl ground truth issue also mentioned in #374 , so I will close this issue
